### ISSUE TITLE
Suggestion for raid sign up

### ISSUE THREAD

**Issue by the-travisty** [Baviaan/lotro#10]
Love the bot, think its a great idea and seems to be very well executed. The only thing I would change is where the error messages show... Having it post into the channel with the raid signups can cause a lot of spam and means a moderator has to be on top of it all day.

Would it be better to pass the errors via a DM? Specifically the ones directed at individuals when signing up

Just a thought. Thanks
Trav

**Comment by Baviaan** [comment]
Sorry I didn't see this earlier. The bot could attempt to send a DM but it's up to the individual's settings (if they allow DMs from everyone) whether it would arrive. Also the message will be automatically deleted after 15s, so I don't really see the problem with it currently.

If you're worried about notifications I would suggest changing it to mentions only for your raid channel. You can leave notifications on for the calendar channel to be notified when an actual raid is posted.

**Comment by Baviaan** [comment]
The sign up error messages are now ephemeral, meaning they're only visible to whoever triggered them.
